sysrepoctl MAINTENANCE check return value of asprintf (#3624)
build fails with latest sysrepo version due to compiler warning for
unused result being treated as error due to -Werror flag.

/usr/src/packages/BUILD/src/executables/sysrepoctl.c:440:13:
error: ignoring return value of 'asprintf' declared with
attribute 'warn_unused_result' [-Werror=unused-result]
asprintf(&cur_item->name, " %s", ly_mod->parsed->includes[u]
                                    .submodule->name);