cmake: Fix protobuf-c invocation once again
This builds on top of 1b56f984c70569fa2832451c9716525a7e4b9d40;
apparently, my change was not enough for at least some versions of CMake
and Ninja:

  + ninja-build install
  [1/140] cd /home/turbo-hipster/jobs/...
  [2/140] Building C object tests/CMakeFiles/HELPERS.dir/helpers/test_module_helper.c.o
  FAILED: tests/CMakeFiles/HELPERS.dir/helpers/test_module_helper.c.o
  /opt/rh/devtoolset-6/root/usr/bin/cc   -I. -I../inc -I/home/turbo-hipster/target/include -I../src -I../src/clientlib -I../src/common -Isrc/common -I../tests/helpers -Itests/helpers -Wall -Wpedantic -std=gnu11 -Wno-strict-aliasing -g -O0 -MD -MT tests/CMakeFiles/HELPERS.dir/helpers/test_module_helper.c.o -MF tests/CMakeFiles/HELPERS.dir/helpers/test_module_helper.c.o.d -o tests/CMakeFiles/HELPERS.dir/helpers/test_module_helper.c.o   -c ../tests/helpers/test_module_helper.c
  In file included from ../tests/helpers/test_module_helper.h:26:0,
                   from ../tests/helpers/test_module_helper.c:22:
  ../src/data_manager.h:30:26: fatal error: sysrepo.pb-c.h: No such file or directory
   #include "sysrepo.pb-c.h"
                            ^
  compilation terminated.

When I tried to fix this, I forgot that the HELPERS also include files such as
the data_manager.h which in turn depend on the generated .h.